name: Frost-Football
version: 2.0.0
api: 5.0.0
main: devil\football\Football
author: _devil_xd

permissions:
  FrostFootball.use.cmd:
    default: op
    description: Allow players to use the football command
  FrostFootball.spawn.cmd:
    default: op
    description: Allow players to spawn footballs
  FrostFootball.remove.cmd:
    default: op
    description: Allow players to remove all footballs

commands:
  football:
    description: Football Command
    usage: /football <spawn | remove> [count]
    permission: FrostFootball.use.cmd
    aliases: [fb]
